/**
 * Renders the Tier 1 Platform Validation Report (ADR-018 D9) from the vitest
 * JSON report produced by the preceding test step, and writes it as Markdown.
 *
 * Two modes, detected via GITHUB_ACTIONS:
 *   - CI: written to validation-reports/ (generated output, gitignored,
 *     retained via the workflow's upload-artifact step instead of git).
 *   - Local (predeploy hook, Phase 31A): written to docs/validation-reports/
 *     and MUST be committed — a local deploy has no CI artifact retaining it,
 *     so the report only survives as a quality record (clause 8.4) if it's
 *     in version control. Also records machine, user, commit SHA, working
 *     tree cleanliness, and deploy target, none of which apply in CI.
 *
 * Must run after the vitest JSON report has been written (i.e. after
 * `npm test`, which always emits test-results/vitest-report.json).
 *
 * Usage:
 *   npx tsx scripts/writePlatformValidationReport.ts
 */

import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import { execSync } from 'node:child_process';

const ROOT = path.resolve(__dirname, '..');
const IS_CI = process.env.GITHUB_ACTIONS === 'true';

function git(args: string): string {
  return execSync(`git ${args}`, { cwd: ROOT }).toString().trim();
}

function readJson(filePath: string): any {
  return JSON.parse(fs.readFileSync(filePath, 'utf-8'));
}

function formatBangkok(date: Date): string {
  return new Intl.DateTimeFormat('en-GB', {
    timeZone: 'Asia/Bangkok',
    dateStyle: 'medium',
    timeStyle: 'long',
  }).format(date);
}

function formatDuration(testReport: any): string {
  const start = testReport.startTime;
  const endTimes = Array.isArray(testReport.testResults)
    ? testReport.testResults
        .map((r: any) => r.endTime)
        .filter((t: any) => typeof t === 'number')
    : [];
  if (typeof start !== 'number' || endTimes.length === 0) return 'unknown';
  const end = Math.max(...endTimes);
  return `${((end - start) / 1000).toFixed(2)}s`;
}

function main() {
  const testReportPath = path.join(ROOT, 'test-results', 'vitest-report.json');
  if (!fs.existsSync(testReportPath)) {
    console.error(
      `Test report not found at ${testReportPath}. This script must run after the vitest JSON reporter step.`
    );
    process.exit(1);
  }
  const testReport = readJson(testReportPath);
  const pkgJson = readJson(path.join(ROOT, 'package.json'));
  const vitestPkgPath = path.join(ROOT, 'node_modules', 'vitest', 'package.json');
  const vitestVersion = fs.existsSync(vitestPkgPath) ? readJson(vitestPkgPath).version : 'unknown';
  const npmVersion = execSync('npm --version').toString().trim();

  const now = new Date();
  const sha = IS_CI ? (process.env.GITHUB_SHA ?? 'unknown') : git('rev-parse HEAD');
  const branch = IS_CI ? (process.env.GITHUB_REF_NAME ?? 'unknown') : git('rev-parse --abbrev-ref HEAD');

  const lines: string[] = ['# Platform Validation Report', ''];

  if (IS_CI) {
    const runId = process.env.GITHUB_RUN_ID ?? 'unknown';
    const serverUrl = process.env.GITHUB_SERVER_URL ?? 'https://github.com';
    const repo = process.env.GITHUB_REPOSITORY ?? 'unknown/unknown';
    const runUrl = `${serverUrl}/${repo}/actions/runs/${runId}`;
    lines.push(
      `- **Run date (UTC):** ${now.toISOString()}`,
      `- **Run date (Asia/Bangkok):** ${formatBangkok(now)}`,
      `- **Commit SHA:** ${sha}`,
      `- **Branch:** ${branch}`,
      `- **Workflow run:** [${runId}](${runUrl})`,
      ''
    );
  } else {
    const dirty = git('status --porcelain').length > 0;
    const target =
      process.env.DEPLOY_TARGET_LABEL ??
      'live (unconfirmed — Firebase does not expose the deploy target to predeploy ' +
        'hooks; set DEPLOY_TARGET_LABEL before deploying to record it accurately, ' +
        'e.g. DEPLOY_TARGET_LABEL="channel:phase31a-verify")';
    lines.push(
      '**LOCAL DEPLOY** — this report was generated by a predeploy hook running on ' +
        'an operator\'s machine, not in CI.',
      ''
    );
    if (dirty) {
      lines.push(
        '> **WORKING TREE WAS DIRTY AT DEPLOY TIME.** Uncommitted changes were present. ' +
          'The deployed build may not correspond to any commit and cannot be fully ' +
          'reproduced from git history alone.',
        ''
      );
    }
    lines.push(
      `- **Run date (UTC):** ${now.toISOString()}`,
      `- **Run date (Asia/Bangkok):** ${formatBangkok(now)}`,
      `- **Commit SHA:** ${sha}`,
      `- **Branch:** ${branch}`,
      `- **Working tree:** ${dirty ? 'DIRTY (uncommitted changes present)' : 'CLEAN'}`,
      `- **Deploy target:** ${target}`,
      `- **Machine:** ${os.hostname()}`,
      `- **User:** ${os.userInfo().username}`,
      ''
    );
  }

  lines.push(
    '## Test suite result',
    '',
    `- **Test files:** ${Array.isArray(testReport.testResults) ? testReport.testResults.length : 'unknown'}`,
    `- **Tests:** ${testReport.numTotalTests ?? 'unknown'}`,
    `- **Passed:** ${testReport.numPassedTests ?? 'unknown'}`,
    `- **Failed:** ${testReport.numFailedTests ?? 'unknown'}`,
    `- **Skipped:** ${testReport.numPendingTests ?? 'unknown'}`,
    `- **Duration:** ${formatDuration(testReport)}`,
    '',
    '## Tooling',
    '',
    `- **Node version:** ${process.version}`,
    `- **npm version:** ${npmVersion}`,
    `- **vitest version:** ${vitestVersion}`,
    `- **App version:** ${pkgJson.version}`,
    '',
    '## Scope of this evidence',
    '',
    'Tier 1 platform validation per ADR-018 D9. Covers the expression interpreter, ' +
      'number formatting and round-on-display rules, unit conversion, PDF rendering ' +
      'and Firestore rules to the extent exercised by the automated suite. It does ' +
      'NOT constitute validation of any individual Recorder Template version.',
    ''
  );

  const outDir = IS_CI ? path.join(ROOT, 'validation-reports') : path.join(ROOT, 'docs', 'validation-reports');
  fs.mkdirSync(outDir, { recursive: true });
  const shaShort = sha === 'unknown' ? 'unknown' : sha.slice(0, 12);
  const outPath = IS_CI
    ? path.join(outDir, `platform-validation-${shaShort}.md`)
    : path.join(
        outDir,
        `platform-validation-local-${now.toISOString().replace(/[:.]/g, '-')}-${shaShort}.md`
      );
  fs.writeFileSync(outPath, lines.join('\n'), 'utf-8');
  console.log(`Platform Validation Report written to ${outPath}`);
  if (!IS_CI) {
    console.log(
      `Reminder: this report is a quality record (clause 8.4) and must be committed — ` +
        `git add "${path.relative(ROOT, outPath)}" && git commit`
    );
  }
}

main();
